# Generated by Django 4.0.4 on 2022-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя объекта')),
                ('client_id', models.CharField(max_length=150, verbose_name='client_id')),
                ('client_secret', models.CharField(max_length=150, verbose_name='client_secret')),
                ('domain', models.CharField(max_length=150, verbose_name='domain_in_bitrix')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_token', models.CharField(max_length=150, verbose_name='access_token')),
                ('rfh_token', models.CharField(max_length=150, verbose_name='refresh_token')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания пары токенов')),
            ],
        ),
    ]
